config/routes.rb
ToDoApp::Application.routes.draw do
  resources :task_values do
    collection do
      get 'task_values_publish_mark'
      get 'task_values_publish_unmark'
    end
  end

  resources :do_lists do
    collection do
      get 'do_lists_publish_mark'
      get 'do_lists_publish_unmark'
    end
  end

  root :to => 'do_lists#index'

end

app/models/do_list.rb
class DoList
  include Mongoid::Document
  include Mongoid::Timestamps

  field :task, type: String
  # field :task_values, type: String
  field :task_publish, type: Boolean, :default => false

end

app/models/task_value.rb
class TaskValue
  include Mongoid::Document
  include Mongoid::Timestamps

  field :task_values, type: String
  field :task_values_publish, type: Boolean, :default => false

  belongs_to :do_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/do_lists_controller.rb
class DoListsController < ApplicationController
  before_action :set_do_list, only: [:show, :edit, :update, :destroy]

  # GET /do_lists
  # GET /do_lists.json
  def index
    # @do_lists = DoList.all
    @do_lists_true = DoList.where(:task_publish => true)
    @do_lists_false = DoList.where(:task_publish => false)
  end

  # GET /do_lists/1
  # GET /do_lists/1.json
  def show
  end

  # GET /do_lists/new
  def new
    @do_list = DoList.new
  end

  # GET /do_lists/1/edit
  def edit
  end

  # POST /do_lists
  # POST /do_lists.json
  def create
    @do_list = DoList.new(do_list_params)

    # puts "---------#{do_list_params}"
    # do_list_params.split(',').each do |x|
    #   TaskValues.create(:task_values => x)
    # end

    respond_to do |format|
      if @do_list.save
        format.html { redirect_to do_lists_url, notice: 'Do list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @do_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /do_lists/1
  # PATCH/PUT /do_lists/1.json
  def update
    respond_to do |format|
      if @do_list.update(do_list_params)
        format.html { redirect_to do_lists_url, notice: 'Do list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /do_lists/1
  # DELETE /do_lists/1.json
  def destroy
    @do_list.destroy
    respond_to do |format|
      format.html { redirect_to do_lists_url }
      format.json { head :no_content }
    end
  end


  def do_lists_publish_mark
    if params[:task_id]
      @output = DoList.where(:id => params[:task_id])
      if @output
        @output.update(:task_publish => true)
      end

      output_task_values = TaskValue.where(:do_lists_id => params[:task_id])
      data = "<h1>Task Name</h1><br/> <h4 style='color:green;font-size:22px'>"+@output.first.task+"</h4> <br/><h2>Task Details</b><br/><br/>"

      output_task_values.each do |x|
        if x.task_values_publish == true
          publish = "Mark"
        else
          publish = "Unmark"
        end
        data.concat("<div style='display: inline'><h4 style='color:green'>"+x.task_values+" => "+publish+"</h4></div>")
      end

      RestClient.post "https://api:key-07d67720afff84541f77fa15d0bc577a@api.mailgun.net/v3/sandboxa7b3b25f08344ca38d6628f09494ceb7.mailgun.org/messages", :from => "Mailgun Task List <postmaster@sandboxa7b3b25f08344ca38d6628f09494ceb7.mailgun.org>", :to => "Dev <dev.jangra031@gmail.com>", :subject => "Task List Done", :html => data
      redirect_to do_lists_url
    end
  end

  def do_lists_publish_unmark
    if params[:task_id]
      @output = DoList.where(:id => params[:task_id])
      if @output
        @output.update(:task_publish => false)
      end
      redirect_to do_lists_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_do_list
      @do_list = DoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def do_list_params
      params.require(:do_list).permit(:task,:task_values)
    end
end

app/controllers/task_values_controller.rb
class TaskValuesController < ApplicationController
  before_action :set_task_value, only: [:show, :edit, :update, :destroy]

  # GET /task_values
  # GET /task_values.json
  def index
    if params[:task_id]
      task_id = params[:task_id]
      @task_values_true = TaskValue.where(:do_lists_id => task_id,:task_values_publish => true)
      @task_values_false = TaskValue.where(:do_lists_id => task_id,:task_values_publish => false)
    end
  end

  # GET /task_values/1
  # GET /task_values/1.json
  def show
  end

  # GET /task_values/new
  def new
    @task_value = TaskValue.new
  end

  # GET /task_values/1/edit
  def edit
  end

  # POST /task_values
  # POST /task_values.json
  def create
    @task_value = TaskValue.new(task_value_params)

    respond_to do |format|
      if @task_value.save
        format.html { redirect_to '/task_values?task_id='+task_value_params["do_lists_id"], notice: 'Task value was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task_value }
      else
        format.html { render action: 'new' }
        format.json { render json: @task_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_values/1
  # PATCH/PUT /task_values/1.json
  def update
    respond_to do |format|
      if @task_value.update(task_value_params)
        format.html { redirect_to '/task_values?task_id='+task_value_params["do_lists_id"], notice: 'Task value was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_values/1
  # DELETE /task_values/1.json
  def destroy
    do_lists_id = @task_value.do_lists_id
    @task_value.destroy
    respond_to do |format|
      format.html { redirect_to '/task_values?task_id='+do_lists_id }
      format.json { head :no_content }
    end
  end

  def task_values_publish_mark
    if params[:task_id]
      @output = TaskValue.where(:id => params[:value_id])
      if @output
        @output.update(:task_values_publish => true)
      end
      redirect_to '/task_values?task_id='+params[:task_id]
    end
  end

  def task_values_publish_unmark
    if params[:task_id]
      @output = TaskValue.where(:id => params[:value_id])
      if @output
        @output.update(:task_values_publish => false)
      end
      redirect_to '/task_values?task_id='+params[:task_id]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_value
      @task_value = TaskValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_value_params
      params.require(:task_value).permit(:task_values,:do_lists_id,:task_values_publish)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/do_lists_helper.rb
module DoListsHelper
end

app/helpers/task_values_helper.rb
module TaskValuesHelper
end

app/views/do_lists/_form.html.erb
<%= form_for(@do_list) do |f| %>
  <% if @do_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@do_list.errors.count, "error") %> prohibited this do_list from being saved:</h2>

      <ul>
      <% @do_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group">
      <%= f.label :task_name %>
    </div>
    <div class="form-group">
      <%= f.text_field :task %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
</script>

app/views/do_lists/edit.html.erb
<h1>Editing do_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @do_list %> |
<%= link_to 'Back', do_lists_path %>

app/views/do_lists/index.html.erb
<h1>Listing Task Lists</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr><b>Publish False</b></tr>
    <% @do_lists_false.each do |do_list| %>
      <tr>
        <td><a href="/task_values?task_id=<%= do_list.id %>"><%= do_list.task %></a></td>
        <td><a href="/task_values/new?task_id=<%= do_list.id %>">Add task details</a></td>
        <!-- <td><%= link_to 'Show', do_list %></td> -->
        <td><%= link_to 'Edit', edit_do_list_path(do_list) %></td>
        <td><%= link_to 'Destroy', do_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Mark', "/do_lists/do_lists_publish_mark?task_id=#{do_list.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>
<br/>
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr><b>Publish True</b></tr>
    <% @do_lists_true.each do |do_list| %>
      <tr>
        <td><a href="/task_values?task_id=<%= do_list.id %>"><%= do_list.task %></a></td>
        <td><a href="/task_values/new?task_id=<%= do_list.id %>">Add task details</a></td>
        <!-- <td><%= link_to 'Show', do_list %></td> -->
        <td><%= link_to 'Edit', edit_do_list_path(do_list) %></td>
        <td><%= link_to 'Destroy', do_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Unmark', "/do_lists/do_lists_publish_unmark?task_id=#{do_list.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Do list', new_do_list_path %>

app/views/do_lists/new.html.erb
<h1>New do_list</h1>

<%= render 'form' %>

<%= link_to 'Back', do_lists_path %>

app/views/do_lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_do_list_path(@do_list) %> |
<%= link_to 'Back', do_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/task_values/_form.html.erb
<%= form_for(@task_value) do |f| %>
  <% if @task_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_value.errors.count, "error") %> prohibited this task_value from being saved:</h2>

      <ul>
      <% @task_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group">
      <%= f.label :task_value %>
    </div>
    <div class="form-group">
      <%= f.text_field :task_values %>
      <%= f.text_field :do_lists_id, :type => 'hidden', :value => params[:task_id] %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_values/edit.html.erb
<h1>Editing task_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_value %> |
<%= link_to 'Back', task_values_path %>

app/views/task_values/index.html.erb
<h1>Listing Task Values</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr><b>Publish False</b></tr>
    <% @task_values_false.each do |task_value| %>
      <tr>
        <td><%= task_value.task_values %></td>
        <!-- <td><%= link_to 'Show', task_value %></td> -->
        <td><%= link_to 'Edit', "/task_values/#{task_value.id}/edit?task_id="+params[:task_id] %></td>
        <td><%= link_to 'Destroy', "/task_values/#{task_value.id}?task_id="+params[:task_id], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Mark', "/task_values/task_values_publish_mark?task_id="+params[:task_id]+"&value_id=#{task_value.id}" %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<br/>
<br/>
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr><b>Publish True</b></tr>
    <% @task_values_true.each do |task_value| %>
      <tr>
        <td><%= task_value.task_values %></td>
        <!-- <td><%= link_to 'Show', task_value %></td> -->
        <td><%= link_to 'Edit', "/task_values/#{task_value.id}/edit?task_id="+params[:task_id] %></td>
        <td><%= link_to 'Destroy', "/task_values/#{task_value.id}?task_id="+params[:task_id], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Unmark', "/task_values/task_values_publish_unmark?task_id="+params[:task_id]+"&value_id=#{task_value.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', '/do_lists' %>

<%= link_to 'New Task value', '/task_values/new?task_id='+params[:task_id] %>

app/views/task_values/new.html.erb
<h1>New task_value</h1>

<%= render 'form' %>

<%= link_to 'Back', '/task_values?task_id='+params[:task_id] %>

app/views/task_values/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_value_path(@task_value) %> |
<%= link_to 'Back', task_values_path %>